export const SET_INPUT_FORSEARCH_USER_ADMIN = "SET_INPUT_FORSEARCH_USER_ADMIN";
export const SET_STATUS_FORSEARCH_USER_ADMIN =
  "SET_STATUS_FORSEARCH_USER_ADMIN";
export const SET_LENGTH_OF_REPORTS_USER = "SET_LENGTH_OF_REPORTS_USER";
