export const SET_INPUT_TO_SEARCH_USER_FOR_WRITE_NEW_MESSAGE =
  "SET_INPUT_TO_SEARCH_USER_FOR_WRITE_NEW_MESSAGE";
export const SHOW_CONVERSATION_SEARCH = "SHOW_CONVERSATION_SEARCH";
export const HIDE_CONVERSATION_SEARCH = "HIDE_CONVERSATION_SEARCH";
export const SET_CONVERSATION_DETAIL = "SET_CONVERSATION_DETAIL";
export const GET_CONVERSATIONS_BY_USER_ID = "GET_CONVERSATIONS_BY_USER_ID";
export const GET_LIST_NUMBER_OF_NOT_READ_YET_MESSAGES_PER_CONVERSATION_BY_USER =
  "GET_LIST_NUMBER_OF_NOT_READ_YET_MESSAGES_PER_CONVERSATION_BY_USER";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const SET_CONVERSATION_TO_DEL = "SET_CONVERSATION_TO_DEL";
