export const GET_LAST_MESSAGES_BY_USER = "GET_LAST_MESSAGES_BY_USER";
export const GET_ALL_MESSAGES_BY_CONVERSATION =
  "GET_ALL_MESSAGES_BY_CONVERSATION";
export const GET_NUMBER_OF_NOT_READ_MESSAGES =
  "GET_NUMBER_OF_NOT_READ_MESSAGES";
