const SHOW_FOLLOWS_LIST_MODAL = "SHOW_FOLLOWS_LIST_MODAL";
const CLOSE_FOLLOWS_LIST_MODAL = "CLOSE_FOLLOWS_LIST_MODAL";
const SHOW_FOLLOWINGS_LIST_MODAL = "SHOW_FOLLOWINGS_LIST_MODAL";
const CLOSE_FOLLOWINGS_LIST_MODAL = "CLOSE_FOLLOWINGS_LIST_MODAL";

export {
  SHOW_FOLLOWINGS_LIST_MODAL,
  SHOW_FOLLOWS_LIST_MODAL,
  CLOSE_FOLLOWINGS_LIST_MODAL,
  CLOSE_FOLLOWS_LIST_MODAL,
};
