const SHOW_FOLLOWS_LIST_MODAL = "SHOW_FOLLOWS_LIST_MODAL";
const CLOSE_FOLLOWS_LIST_MODAL = "CLOSE_FOLLOWS_LIST_MODAL";
const SHOW_FOLLOWINGS_LIST_MODAL = "SHOW_FOLLOWINGS_LIST_MODAL";
const CLOSE_FOLLOWINGS_LIST_MODAL = "CLOSE_FOLLOWINGS_LIST_MODAL";
const SHOW_POST_LIKES_MODAL = "SHOW_POST_LIKES_MODAL";
const CLOSE_POST_LIKES_MODAL = "CLOSE_POST_LIKES_MODAL";
const SHOW_REPLIES = "SHOW_REPLIES";
const CLOSE_REPLIES = "CLOSE_REPLIES";
const SHOW_COMMENT_LIKES_MODAL = "SHOW_COMMENT_LIKES_MODAL";
const CLOSE_COMMENT_LIKES_MODAL = "CLOSE_COMMENT_LIKES_MODAL";
const SHOW_NOS = "SHOW_NOS";
const CLOSE_NOS = "CLOSE_NOS";

export {
  SHOW_FOLLOWINGS_LIST_MODAL,
  SHOW_FOLLOWS_LIST_MODAL,
  CLOSE_FOLLOWINGS_LIST_MODAL,
  CLOSE_FOLLOWS_LIST_MODAL,
  SHOW_COMMENT_LIKES_MODAL,
  CLOSE_COMMENT_LIKES_MODAL,
  SHOW_POST_LIKES_MODAL,
  CLOSE_POST_LIKES_MODAL,
  SHOW_REPLIES,
  CLOSE_REPLIES,
  SHOW_NOS,
  CLOSE_NOS,
};
