const SHOW_FOLLOWS_LIST_MODAL = "SHOW_FOLLOWS_LIST_MODAL";
const CLOSE_FOLLOWS_LIST_MODAL = "CLOSE_FOLLOWS_LIST_MODAL";
const SHOW_FOLLOWINGS_LIST_MODAL = "SHOW_FOLLOWINGS_LIST_MODAL";
const CLOSE_FOLLOWINGS_LIST_MODAL = "CLOSE_FOLLOWINGS_LIST_MODAL";
const SHOW_POST_LIKES_MODAL = "SHOW_POST_LIKES_MODAL";
const CLOSE_POST_LIKES_MODAL = "CLOSE_POST_LIKES_MODAL";
const SHOW_REPLIES = "SHOW_REPLIES";
const CLOSE_REPLIES = "CLOSE_REPLIES";
const SHOW_COMMENT_LIKES_MODAL = "SHOW_COMMENT_LIKES_MODAL";
const CLOSE_COMMENT_LIKES_MODAL = "CLOSE_COMMENT_LIKES_MODAL";
const SHOW_NOS = "SHOW_NOS";
const CLOSE_NOS = "CLOSE_NOS";
const SHOW_DEL_NO = "SHOW_DEL_NO";
const CLOSE_DEL_NO = "CLOSE_DEL_NO";
const SHOW_CREATE_POST_MODAL = "SHOW_CREATE_POST_MODAL";
const CLOSE_CREATE_POST_MODAL = "CLOSE_CREATE_POST_MODAL";
const SHOW_DEL_CON_MODAL = "SHOW_DEL_CON_MODAL";
const CLOSE_DEL_CON_MODAL = "CLOSE_DEL_CON_MODAL";
const SHOW_DEL_CON_CONFIRM_MODAL = "SHOW_DEL_CON_CONFIRM_MODAL";
const CLOSE_DEL_CON_CONFIRM_MODAL = "CLOSE_DEL_CON_CONFIRM_MODAL";
const SHOW_REPORT_MODAL = "SHOW_REPORT_MODAL";
const CLOSE_REPORT_MODAL = "CLOSE_REPORT_MODAL";
const SHOW_CREATE_REPORT_CONFIRM = "SHOW_CREATE_REPORT_CONFIRM";
const CLOSE_CREATE_REPORT_CONFIRM = "CLOSE_CREATE_REPORT_CONFIRM";
export {
  SHOW_FOLLOWINGS_LIST_MODAL,
  SHOW_FOLLOWS_LIST_MODAL,
  CLOSE_FOLLOWINGS_LIST_MODAL,
  CLOSE_FOLLOWS_LIST_MODAL,
  SHOW_COMMENT_LIKES_MODAL,
  CLOSE_COMMENT_LIKES_MODAL,
  SHOW_POST_LIKES_MODAL,
  CLOSE_POST_LIKES_MODAL,
  SHOW_REPLIES,
  CLOSE_REPLIES,
  SHOW_NOS,
  CLOSE_NOS,
  CLOSE_DEL_NO,
  SHOW_DEL_NO,
  CLOSE_CREATE_POST_MODAL,
  SHOW_CREATE_POST_MODAL,
  SHOW_DEL_CON_CONFIRM_MODAL,
  SHOW_DEL_CON_MODAL,
  CLOSE_DEL_CON_CONFIRM_MODAL,
  CLOSE_DEL_CON_MODAL,
  SHOW_CREATE_REPORT_CONFIRM,
  SHOW_REPORT_MODAL,
  CLOSE_CREATE_REPORT_CONFIRM,
  CLOSE_REPORT_MODAL,
};
