const GET_ALL_POST = "GET_ALL_POST";
const GET_POSTS_BY_FOLLOWINGS = "GET_POSTS_BY_FOLLOWINGS";
const GET_POST_BY_ID = "GET_POST_BY_ID";
export { GET_ALL_POST, GET_POSTS_BY_FOLLOWINGS, GET_POST_BY_ID };
