export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const SET_COIN_GOLD_STORE = "SET_COIN_GOLD_STORE";
export const SET_ITEM_TYPE_STORE = "SET_ITEM_TYPE_STORE";
export const SET_ITEM_TO_BUY = "SET_ITEM_TO_BUY";
export const SET_USER_TO_GIVE = "SET_USER_TO_GIVE";
