export const SET_INPUT_TO_SEARCH_TRANSACTION =
  "SET_INPUT_TO_SEARCH_TRANSACTION";
export const SET_COIN_OR_GOLD = "SET_COIN_OR_GOLD";
export const SET_TRAN_TYPE = "SET_TRAN_TYPE";
export const SET_MIN_DATE = "SET_MIN_DATE";
export const SET_MAX_DATE = "SET_MAX_DATE";
export const GET_TRANS_BY_USER = "GET_TRANS_BY_USER";
