const GET_ALL_USERS = "GET_ALL_USERS";
const SET_FOLLOWS_BAR = "SET_FOLLOWS_BAR";
const SET_USER_LOGEDIN = "SET_USER_LOGEDIN";
const SET_USER_DETAIL = "SET_USERNAME_DETAIL";
export { GET_ALL_USERS, SET_FOLLOWS_BAR, SET_USER_DETAIL, SET_USER_LOGEDIN };
