const GET_ALL_USERS = "GET_ALL_USERS";
const SET_FOLLOWS_BAR = "SET_FOLLOWS_BAR";
const SET_USER_LOGEDIN = "SET_USER_LOGEDIN";
const SET_USER_DETAIL = "SET_USERNAME_DETAIL";
const SET_USER_TO_SHOW_ITEMS = "SET_USER_TO_SHOW_ITEMS";
const SET_INPUT_TO_SEARCH_USER = "SET_INPUT_TO_SEARCH_USER";
export {
  GET_ALL_USERS,
  SET_FOLLOWS_BAR,
  SET_USER_DETAIL,
  SET_USER_LOGEDIN,
  SET_USER_TO_SHOW_ITEMS,
  SET_INPUT_TO_SEARCH_USER,
};
