export const defaultPosts = [
  {
    id: 1,
    userUsername: "nguoicodon",
    userAvatar: "user_1.png",
    content: "Chào mọi người!",
    image: "post_1.png",
    createdAt: "10/10/2022 12:00:00",
    likes: [
      {
        id: 13,
        userUsername: "nguoicodon",
        userAvatar: "user_1.png",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 1,
        userUsername: "queenqueen",
        userAvatar: "user_2.png",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 3,
        userUsername: "thieuthu11",
        userAvatar: "user_3.png",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 4,
        userUsername: "ngocmaitran",
        userAvatar: "user_4.png",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 5,
        userUsername: "handoi22",
        userAvatar: "user_5.png",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 6,
        userUsername: "4cuicamau",
        userAvatar: "user6.jpg",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 7,
        userUsername: "duongcoi",
        userAvatar: "user7.jpg",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 8,
        userUsername: "sh12345",
        userAvatar: "user8.jpg",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 9,
        userUsername: "chiahhh",
        userAvatar: "user10.jpg",
        createdAt: "21/10/2023 10:09:50",
      },
    ],
    comments: [
      {
        id: 1,
        userUsername: "queenqueen",
        userAvatar: "user_2.png",
        content: "OK",
        createdAt: "21/10/2023 10:09:50",
        likes: [
          {
            id: 11,
            userUsername: "nguoicodon",
            userAvatar: "user_1.png",
            createdAt: "21/10/2023 10:09:50",
          },
          {
            id: 12,
            userUsername: "queenqueen",
            userAvatar: "user_2.png",
            createdAt: "21/10/2023 10:09:50",
          },
        ],
      },
      {
        id: 3,
        userUsername: "thieuthu11",
        userAvatar: "user_3.png",
        content: "Úi dồi",
        createdAt: "21/10/2023 10:09:50",
        likes: [],
      },
      {
        id: 6,
        userUsername: "nguoicodon",
        userAvatar: "user_1.png",
        content: "Đã xem:)",
        createdAt: "21/10/2023 10:09:50",
        likes: [],
      },
    ],
    reports: [],
  },
  {
    id: 2,
    userUsername: "nguoicodon",
    userAvatar: "user_1.png",
    content: "Tạm biệt mọi người!",
    image: "post_2.png",
    createdAt: "01/09/2023 12:00:00",
    likes: [
      {
        id: 10,
        userUsername: "nguoicodon",
        userAvatar: "user_1.png",
        createdAt: "21/10/2023 10:09:50",
      },
      {
        id: 2,
        userUsername: "thieuthu11",
        userAvatar: "user_3.png",
        createdAt: "21/10/2023 10:09:50",
      },
    ],
    comments: [
      {
        id: 2,
        userUsername: "thieuthu11",
        userAvatar: "user_3.png",
        content: "Woao",
        createdAt: "21/10/2023 10:09:50",
        likes: [],
      },
      {
        id: 4,
        userUsername: "nguoicodon",
        userAvatar: "user_1.png",
        content: "kkk",
        createdAt: "21/10/2023 10:09:50",
        likes: [],
      },
    ],
    reports: [],
  },
];
export const defaultItem = { name: "Chưa chọn Item", image: "Items.png" };
